package App.Models;

import App.Models.Card.*;

/**
 * Created by calebmacdonaldblack on 29/09/2016.
 */
public class StaticDeckBuilder {

    public Deck buildDeck(){
        Deck deck = new Deck();
        deck.addCard(new RegularCard("Quartz", "Chemistry: SiO_2\nClassification: tectosilicate\nCrystal System: hexagonal\nOccurrences: igneous,metamorphic,sedimentary", new Range(7, 7), new Range(7, 2.65), Cleavage.POOR_NONE, CrustalAbundance.HIGH, EconomicValue.MODERATE));
        deck.addCard(new RegularCard("Plagioclase", "Chemistry: Na Al Si_3 O_8 - Ca Al_2 Si_2 O_8\nClassification: tectosilicate\nCrystal System: triclinic\nOccurrences: igneous,metamorphic,sedimentary", new Range(6, 6.5), new Range(6, 6.5), Cleavage.PERFECT1_GOOD1, CrustalAbundance.VERY_HIGH, EconomicValue.MODERATE));
        deck.addCard(new RegularCard("Orthoclase", "Chemistry: K Al Si_3 O_3\nClassification: tectosilicate\nCrystal System: monoclinic\nOccurrences: igneous,metamorphic,sedimentary", new Range(6, 6.5), new Range(6, 6.5), Cleavage.PERFECT1_GOOD1, CrustalAbundance.HIGH, EconomicValue.MODERATE));
        deck.addCard(new RegularCard("Biotite", "Chemistry: K(Fe, Mg)_3 Al Si_3 O_10 (OH)_2 \nClassification: phyllosilicate\nCrystal System: monoclinic\nOccurrences: igneous,metamorphic", new Range(2.5, 3), new Range(2.5, 3), Cleavage.PERFECT1, CrustalAbundance.MODERATE, EconomicValue.LOW));
        deck.addCard(new RegularCard("Muscovite", "Chemistry: K Al_3 Si_3 O_10 (O H)_2\nClassification: phyllosilicate\nCrystal System: monoclinic\nOccurrences: igneous,metamorphic", new Range(2.5, 3), new Range(2.5, 3), Cleavage.PERFECT1, CrustalAbundance.MODERATE, EconomicValue.MODERATE));
        deck.addCard(new RegularCard("Hornblende", "Chemistry: Ca_2 (Mg, Fe)_4 Al_2 Si_7 O_22 (OH)_2\nClassification: inosilicate\nCrystal System: monoclinic\nOccurrences: igneous,metamorphic", new Range(5, 6), new Range(5, 6), Cleavage.GOOD2, CrustalAbundance.MODERATE, EconomicValue.TRIVIAL));
        deck.addCard(new RegularCard("Actinolite", "Chemistry: Ca_2 (Mg, Fe)_5 Si_8 O_22 (OH)_2\nClassification: inosilicate\nCrystal System: monoclinic\nOccurrences: metamorphic", new Range(5, 6), new Range(5, 6), Cleavage.GOOD2, CrustalAbundance.LOW, EconomicValue.LOW));
        deck.addCard(new RegularCard("Glaucophane", "Chemistry: Na_2 (Mg, Fe)_3 Al_2 Si_8 O_22 (OH)_2 \nClassification: inosilicate\nCrystal System: monoclinic\nOccurrences: metamorphic", new Range(6, 6), new Range(3.0, 3.2), Cleavage.GOOD2, CrustalAbundance.LOW, EconomicValue.TRIVIAL));
        deck.addCard(new RegularCard("Olivine", "Chemistry: (Mg, Fe)_2 Si O_4\nClassification: nesosilicate\nCrystal System: orthorhombic\nOccurrences: igneous,metamorphic,mantle", new Range(6.5, 7), new Range(6.5, 7), Cleavage.POOR2, CrustalAbundance.HIGH, EconomicValue.LOW));
        deck.addCard(new RegularCard("Garnet", "Chemistry: (Fe, Mg, Ca, Mn)_3 (Al, Fe)_2 Si_3 O_12\nClassification: nesosilicate\nCrystal System: isometric\nOccurrences: igneous,metamorphic,mantle", new Range(6, 7.5), new Range(6, 7.5), Cleavage.NONE, CrustalAbundance.MODERATE, EconomicValue.MODERATE));
        deck.addCard(new RegularCard("Titanite", "Chemistry: Ca Ti Si O_5\nClassification: nesosilicate\nCrystal System: monoclinic\nOccurrences: igneous,metamorphic", new Range(5, 5.5), new Range(5, 5.5), Cleavage.GOOD3, CrustalAbundance.LOW, EconomicValue.LOW));
        deck.addCard(new RegularCard("Zircon", "Chemistry: Zr Si O_4\nClassification: nesosilicate\nCrystal System: tetragonal\nOccurrences: igneous,metamorphic,sedimentary", new Range(7.5, 7.5), new Range(4.6, 4.7), Cleavage.POOR2, CrustalAbundance.TRACE, EconomicValue.MODERATE));
        deck.addCard(new RegularCard("Augite", "Chemistry: Ca (Mg, Fe) Si_2 O_6 \nClassification: inosilicate\nCrystal System: monoclinic\nOccurrences: igneous,metamorphic", new Range(5.5, 6.5), new Range(5.5, 6.5), Cleavage.GOOD2, CrustalAbundance.HIGH, EconomicValue.TRIVIAL));
        deck.addCard(new RegularCard("Orthopyroxene", "Chemistry: (Mg, Fe)_2 Si_2 O_6 \nClassification: inosilicate\nCrystal System: orthorhombic\nOccurrences: igneous,metamorphic,mantle", new Range(5, 6), new Range(5, 6), Cleavage.GOOD2, CrustalAbundance.HIGH, EconomicValue.TRIVIAL));
        deck.addCard(new RegularCard("Chlorite", "Chemistry: (Mg, Fe)_5 Al_2 Si_3 O_10 (OH)_8\nClassification: phyllosilicate\nCrystal System: monoclinic\nOccurrences: metamorphic", new Range(2, 3), new Range(2, 3), Cleavage.PERFECT1, CrustalAbundance.MODERATE, EconomicValue.LOW));
        deck.addCard(new RegularCard("Antigorite", "Chemistry: (Mg, Fe)_3 Si_2 O_5 (OH)_4\nClassification: phyllosilicate\nCrystal System: monoclinic\nOccurrences: metamorphic,mantle", new Range(3.5, 4), new Range(3.5, 4), Cleavage.PERFECT1, CrustalAbundance.LOW, EconomicValue.LOW));
        deck.addCard(new RegularCard("Talc", "Chemistry: Mg_3 Si_4 O_10 (OH)_2\nClassification: phyllosilicate\nCrystal System: monoclinic\nOccurrences: metamorphic", new Range(1, 1), new Range(2.6,2.8), Cleavage.PERFECT1, CrustalAbundance.LOW, EconomicValue.MODERATE));
        deck.addCard(new RegularCard("Kaolinite", "Chemistry: Al_2 Si_2 O_5 (OH)_4\nClassification: phyllosilicate\nCrystal System: triclinic\nOccurrences: sedimentary", new Range(1.5, 2.5), new Range(1.5, 2.5), Cleavage.PERFECT1, CrustalAbundance.MODERATE, EconomicValue.HIGH));
        deck.addCard(new RegularCard("Andalusite", "Chemistry: Al_2 Si O_5\nClassification: nesosilicate\nCrystal System: orthorhombic\nOccurrences: metamorphic", new Range(6.5, 7), new Range(6.5, 7), Cleavage.GOOD2, CrustalAbundance.LOW, EconomicValue.MODERATE));
        deck.addCard(new RegularCard("Kyanite", "Chemistry: Al_2 Si O_5\nClassification: nesosilicate\nCrystal System: triclinic\nOccurrences: metamorphic", new Range(5.5, 7), new Range(5.5, 7), Cleavage.PERFECT1_GOOD1, CrustalAbundance.TRACE, EconomicValue.MODERATE));
        deck.addCard(new RegularCard("Sillimanite", "Chemistry: Al_2 Si O_5\nClassification: nesosilicate\nCrystal System: orthorhombic\nOccurrences: igneous,metamorphic", new Range(6.5, 7.5), new Range(6.5, 7.5), Cleavage.PERFECT1_GOOD1, CrustalAbundance.LOW, EconomicValue.LOW));
        deck.addCard(new RegularCard("Staurolite", "Chemistry: (Fe, Mg)_2 Al_9 Si_4 O_22 (OH)_2\nClassification: nesosilicate\nCrystal System: monoclinic\nOccurrences: metamorphic", new Range(7, 7), new Range(3.7,3.8), Cleavage.GOOD1, CrustalAbundance.TRACE, EconomicValue.LOW));
        deck.addCard(new RegularCard("Epidote", "Chemistry: Ca_2 (Al, Fe)_3 Si_3 O_12 (OH)\nClassification: sorosilicate\nCrystal System: monoclinic\nOccurrences: igneous,metamorphic", new Range(6 ,  6.5), new Range(6 ,  6.5), Cleavage.PERFECT1, CrustalAbundance.MODERATE, EconomicValue.TRIVIAL));
        deck.addCard(new RegularCard("Tourmaline", "Chemistry: Na (Mg, Fe)_3 Al_6 B_3 Si_6 O_27 (OH)_4\nClassification: cyclosilicate\nCrystal System: hexagonal\nOccurrences: metamorphic", new Range(7 ,  7.5), new Range(7 ,  7.5), Cleavage.POOR2, CrustalAbundance.TRACE, EconomicValue.MODERATE));
        deck.addCard(new RegularCard("Topaz", "Chemistry: Al_2 Si O_4 (F, OH)_2\nClassification: nesosilicate\nCrystal System: orthorhombic\nOccurrences: metamorphic,sedimentary", new Range(8, 8), new Range(3.5, 3.6), Cleavage.PERFECT1, CrustalAbundance.ULTRATRACE, EconomicValue.LOW));
        deck.addCard(new RegularCard("Beryl", "Chemistry: Be_3 Al_2 Si_6 O_18\nClassification: cyclosilicate\nCrystal System: hexagonal\nOccurrences: igneous,metamorphic", new Range(7.5 ,  8), new Range(7.5 ,  8), Cleavage.POOR1, CrustalAbundance.TRACE, EconomicValue.MODERATE));
        deck.addCard(new RegularCard("Pyrite", "Chemistry: Fe S_2\nClassification: sulfide\nCrystal System: isometric\nOccurrences: igneous,metamorphic", new Range(6 ,  6.5), new Range(6 ,  6.5), Cleavage.POOR2, CrustalAbundance.LOW, EconomicValue.MODERATE));
        deck.addCard(new RegularCard("Pyrrhotite", "Chemistry: Fe_{1-x} S\nClassification: sulfide\nCrystal System: monoclinic\nOccurrences: igneous,metamorphic", new Range(3.5 ,  4.5), new Range(3.5 ,  4.5), Cleavage.NONE, CrustalAbundance.LOW, EconomicValue.MODERATE));
        deck.addCard(new RegularCard("Chalcopyrite", "Chemistry: Cu Fe S_2\nClassification: sulfide\nCrystal System: tetragonal\nOccurrences: igneous,metamorphic", new Range(3.5 ,  4), new Range(3.5 ,  4), Cleavage.POOR2, CrustalAbundance.LOW, EconomicValue.VERY_HIGH));
        deck.addCard(new RegularCard("Galena", "Chemistry: Pb S\nClassification: sulfide\nCrystal System: isometric\nOccurrences: metamorphic", new Range(2.5, 2.5), new Range(7.5, 7.6), Cleavage.PERFECT3, CrustalAbundance.TRACE, EconomicValue.HIGH));
        deck.addCard(new RegularCard("Sphalerite", "Chemistry: (Zn, Fe) S\nClassification: sulfide\nCrystal System: isometric\nOccurrences: metamorphic", new Range(3.5 ,  4), new Range(3.5 ,  4), Cleavage.PERFECT6, CrustalAbundance.TRACE, EconomicValue.HIGH));
        deck.addCard(new RegularCard("Molybdenite", "Chemistry: Mo S_2\nClassification: sulfide\nCrystal System: hexagonal\nOccurrences: igneous,metamorphic", new Range(1 ,  1.5), new Range(1 ,  1.5), Cleavage.PERFECT1, CrustalAbundance.TRACE, EconomicValue.HIGH));
        deck.addCard(new RegularCard("Gold", "Chemistry: Au\nClassification: native element\nCrystal System: isometric\nOccurrences: metamorphic,sedimentary", new Range(2.5 ,  3), new Range(2.5 ,  3), Cleavage.NONE, CrustalAbundance.ULTRATRACE, EconomicValue.IM_RICH));
        deck.addCard(new RegularCard("Diamond", "Chemistry: C\nClassification: native element\nCrystal System: isometric\nOccurrences: igneous,metamorphic,sedimentary", new Range(10, 10), new Range(10, 3.5), Cleavage.PERFECT4, CrustalAbundance.ULTRATRACE, EconomicValue.IM_RICH));
        deck.addCard(new RegularCard("Graphite", "Chemistry: C\nClassification: native element\nCrystal System: hexagonal\nOccurrences: metamorphic,sedimentary", new Range(1 ,  2), new Range(1 ,  2), Cleavage.PERFECT1, CrustalAbundance.TRACE, EconomicValue.MODERATE));
        deck.addCard(new RegularCard("Halite", "Chemistry: Na Cl\nClassification: halide\nCrystal System: isometric\nOccurrences: sedimentary", new Range(2.5, 2.5), new Range(2.5, 2.2), Cleavage.PERFECT3, CrustalAbundance.TRACE, EconomicValue.MODERATE));
        deck.addCard(new RegularCard("Fluorite", "Chemistry: Ca F_2\nClassification: halide\nCrystal System: isometric\nOccurrences: metamorphic", new Range(4, 4), new Range(4, 3.2), Cleavage.PERFECT4, CrustalAbundance.TRACE, EconomicValue.MODERATE));
        deck.addCard(new RegularCard("Gypsum", "Chemistry: Ca S O_4 (H_2 O)_2\nClassification: sulfate\nCrystal System: monoclinic\nOccurrences: metamorphic,sedimentary", new Range(2, 2), new Range(2, 2.3), Cleavage.PERFECT1_GOOD2, CrustalAbundance.TRACE, EconomicValue.HIGH));
        deck.addCard(new RegularCard("Barite", "Chemistry: Ba S O_4\nClassification: sulfate\nCrystal System: orthorhombic\nOccurrences: metamorphic,sedimentary", new Range(3 ,  3.5), new Range(3 ,  3.5), Cleavage.PERFECT2_GOOD1, CrustalAbundance.TRACE, EconomicValue.MODERATE));
        deck.addCard(new RegularCard("Apatite", "Chemistry: Ca_5 (P O_4)_3 (OH, F, Cl)\nClassification: phosphate\nCrystal System: hexagonal\nOccurrences: igneous,metamorphic,sedimentary", new Range(5, 5), new Range(3.1, 3.2), Cleavage.POOR2, CrustalAbundance.LOW, EconomicValue.HIGH));
        deck.addCard(new RegularCard("Monazite", "Chemistry: (La, Ce, Nd) P O_4 \nClassification: phosphate\nCrystal System: monoclinic\nOccurrences: igneous,metamorphic,sedimentary", new Range(5, 5), new Range(5.0, 5.3), Cleavage.GOOD1_POOR1, CrustalAbundance.TRACE, EconomicValue.MODERATE));
        deck.addCard(new RegularCard("Calcite", "Chemistry: Ca C O_3\nClassification: carbonate\nCrystal System: hexagonal\nOccurrences: igneous,metamorphic,sedimentary", new Range(3, 3), new Range(3, 2.7), Cleavage.PERFECT3, CrustalAbundance.MODERATE, EconomicValue.HIGH));
        deck.addCard(new RegularCard("Dolomite", "Chemistry: Ca Mg (C O_3)_2\nClassification: carbonate\nCrystal System: hexagonal\nOccurrences: metamorphic,sedimentary", new Range(3.5 ,  4), new Range(3.5 ,  4), Cleavage.PERFECT3, CrustalAbundance.LOW, EconomicValue.LOW));
        deck.addCard(new RegularCard("Magnesite", "Chemistry: Mg C O_3\nClassification: carbonate\nCrystal System: hexagonal\nOccurrences: metamorphic,sedimentary", new Range(4, 4), new Range(4, 3.0), Cleavage.PERFECT3, CrustalAbundance.LOW, EconomicValue.MODERATE));
        deck.addCard(new RegularCard("Siderite", "Chemistry: Fe C O_3\nClassification: carbonate\nCrystal System: hexagonal\nOccurrences: metamorphic,sedimentary", new Range(4 ,  4.5), new Range(4 ,  4.5), Cleavage.PERFECT3, CrustalAbundance.TRACE, EconomicValue.MODERATE));
        deck.addCard(new RegularCard("Magnetite", "Chemistry: Fe_3 O_4\nClassification: oxide (spinel)\nCrystal System: isometric\nOccurrences: igneous,metamorphic,sedimentary", new Range(5.5 ,  6), new Range(5.5 ,  6), Cleavage.NONE, CrustalAbundance.MODERATE, EconomicValue.VERY_HIGH));
        deck.addCard(new RegularCard("Hematite", "Chemistry: Fe_2 O_3\nClassification: oxide\nCrystal System: hexagonal\nOccurrences: metamorphic,sedimentary", new Range(5 ,  6), new Range(5 ,  6), Cleavage.NONE, CrustalAbundance.TRACE, EconomicValue.HIGH));
        deck.addCard(new RegularCard("Chromite", "Chemistry: (Fe, Mg) Cr_2 O_4\nClassification: oxide (spinel)\nCrystal System: isometric\nOccurrences: igneous,sedimentary", new Range(5.5, 5.5), new Range(4.5, 5.1), Cleavage.NONE, CrustalAbundance.LOW, EconomicValue.HIGH));
        deck.addCard(new RegularCard("Ilmenite", "Chemistry: Ti Fe O_3\nClassification: oxide\nCrystal System: hexagonal\nOccurrences: igneous,metamorphic,sedimentary", new Range(5 ,  6), new Range(5 ,  6), Cleavage.NONE, CrustalAbundance.LOW, EconomicValue.MODERATE));
        deck.addCard(new RegularCard("Rutile", "Chemistry: Ti O_2\nClassification: oxide\nCrystal System: tetragonal\nOccurrences: metamorphic,sedimentary", new Range(6 ,  6.5), new Range(6 ,  6.5), Cleavage.GOOD2, CrustalAbundance.LOW, EconomicValue.HIGH));
        deck.addCard(new RegularCard("Corundum", "Chemistry: Al_2 O_3\nClassification: oxide\nCrystal System: hexagonal\nOccurrences: metamorphic,sedimentary", new Range(9, 9), new Range(4.0, 9), Cleavage.NONE, CrustalAbundance.TRACE, EconomicValue.MODERATE));
        deck.addCard(new RegularCard("Cassiterite", "Chemistry: Sn O_2\nClassification: oxide\nCrystal System: tetragonal\nOccurrences: igneous,metamorphic,sedimentary", new Range(6 ,  7), new Range(6 ,  7), Cleavage.GOOD1_POOR1, CrustalAbundance.TRACE, EconomicValue.HIGH));
        deck.addCard(new RegularCard("Gibbsite", "Chemistry: Al (O H)_3\nClassification: hydroxide\nCrystal System: monoclinic\nOccurrences: metamorphic,sedimentary", new Range(2.5 ,  3.5), new Range(2.5 ,  3.5), Cleavage.PERFECT1, CrustalAbundance.LOW, EconomicValue.HIGH));
        deck.addCard(new RegularCard("Goethite", "Chemistry: Fe O (OH)\nClassification: hydroxide\nCrystal System: orthorhombic\nOccurrences: sedimentary", new Range(5 ,  5.5), new Range(5 ,  5.5), Cleavage.PERFECT1_GOOD1, CrustalAbundance.MODERATE, EconomicValue.MODERATE));
        deck.addCard(new TrumpCard("The Miner", "Economic value", new TrumpCategory[]{TrumpCategory.ECONOMIC_VALUE}));
        deck.addCard(new TrumpCard("The Petrologist", "Crustal abundance", new TrumpCategory[]{TrumpCategory.CRUSTAL_ABUNDANCE}));
        deck.addCard(new TrumpCard("The Gemmologist", "Hardness", new TrumpCategory[]{TrumpCategory.HARDNESS}));
        deck.addCard(new TrumpCard("The Mineralogist", "Cleavage", new TrumpCategory[]{TrumpCategory.CLEAVAGE}));
        deck.addCard(new TrumpCard("The Geophysicist", "Specific gravity", new TrumpCategory[]{TrumpCategory.SPECIFIC_GRAVITY}));
        deck.addCard(new TrumpCard("The Geologist", "Change to trumps category of your choice", new TrumpCategory[]{TrumpCategory.ECONOMIC_VALUE, TrumpCategory.SPECIFIC_GRAVITY, TrumpCategory.CLEAVAGE, TrumpCategory.HARDNESS, TrumpCategory.CRUSTAL_ABUNDANCE}));
        return deck;
    }
}
